# Generated by Django 4.2 on 2023-04-23 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_review_like_count_review_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="dislikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
