# Generated by Django 4.2 on 2023-04-25 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_review_dislikes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-date_added"]},
        ),
    ]
