# Generated by Django 4.2 on 2023-04-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
        ("main", "0003_review_author_review_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="category",
        ),
        migrations.AlterField(
            model_name="review",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="companies.company",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
