# Generated by Django 4.2 on 2023-04-23 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WrongCompanyInfoReprot",
            new_name="WrongCompanyInfoReport",
        ),
    ]
