# Generated by Django 4.2 on 2023-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(default="pantera", editable=False),
            preserve_default=False,
        ),
    ]
