# Generated by Django 4.2 on 2023-04-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_company_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_name", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=25)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zip_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PaymentOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="delivery_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="social_media_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="company",
            name="category",
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="companies.address",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_options",
            field=models.ManyToManyField(
                blank=True, related_name="shops", to="companies.paymentoption"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="category",
            field=models.ManyToManyField(related_name="shops", to="companies.category"),
        ),
    ]
