# Generated by Django 4.2 on 2023-04-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_submitted_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["-date_added"], "verbose_name_plural": "Companies"},
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
