# Generated by Django 4.2 on 2023-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_rename_wrongcompanyinforeprot_wrongcompanyinforeport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
