# Generated by Django 4.2 on 2023-04-17 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_address_paymentoption_company_delivery_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "addresses"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
